name: Reset packages
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/packages_reset.yaml
jobs:
  packages:
    runs-on: ubuntu-latest
    container:
      image: "docker://&bioc.CONTAINER_BASE_IMAGE"
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Copy old run
        run: |
          STARTTIME="$(cat runstarttime)" || true
          LOGDIR="logs/$(cat runstarttime)" || true
          mv runstarttime "$LOGDIR"/ || true
          mv alldeps.json "$LOGDIR"/ || true
          mv directdeps.json "$LOGDIR"/ || true
          mv packages.json "$LOGDIR"/ || true
          mv tobuild.txt "$LOGDIR"/ || true
          mv lists "$LOGDIR"/lists || true

      - run: |
          bash .github/scripts/reset_packages.sh
